doks:
    baseurl:
    color_theme: blue
    header:
        logo:
            text: Mastering the Marketplace Learning Library
            image: ./images/Azure_Store_Marketplace.png
        nav:
            - item_name: Item 1
              item_url: '#'
            - item_name: Item 2
              item_url: '#'
            - item_name: Item 3
              item_url: '#'
    google_analytics:
        tracking_code: G-QFBKKPKXNV

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
