site_name: Mastering the Marketplace
site_url: https://microsoft.github.io/Mastering-the-Marketplace/
repo_url: https://github.com/microsoft/Mastering-the-Marketplace
repo_name: microsoft/Mastering-the-Marketplace
edit_uri: ''
extra_css: 
    - stylesheets/extra.css

nav:
  - Content by offer type:
    - Azure Managed Application offers: '/Mastering-the-Marketplace/ama/'
    - Container offers for K8s apps: '/Mastering-the-Marketplace/container/'
    - SaaS offers: '/Mastering-the-Marketplace/saas/'
    - Virtual Machine offers: '/Mastering-the-Marketplace/vm/'
    - Teams offers: '/Mastering-the-Marketplace/teams/'
  - Bonus content:
    - SaaS Accelerator: '/Mastering-the-Marketplace/saas-accelerator/'
    - Partner Center: '/Mastering-the-Marketplace/partner-center/'
    - Select your offer type: '/Mastering-the-Marketplace/misc/select-offer-type'
  - Other:
    - Content for customers: '/Mastering-the-Marketplace/learning-paths/customer'
    - Learning paths: '/Mastering-the-Marketplace/learning-paths/'
    - Site change log: '/Mastering-the-Marketplace/misc/change-log'
    - ✉️ Contact us: 'https://forms.office.com/r/0gCrzhSMkw'

theme:
  features:
    - navigation.sections
    - navigation.expand
  name: material
  custom_dir: overrides
  palette: 
    primary: '#0078D4'
    accent: 'light blue'
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/brands/microsoft
  favicon: favicon.ico

extra: 
  homepage: https://microsoft.github.io/Mastering-the-Marketplace/
  generator: false

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - toc:
        permalink: "#"
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - search:
        indexing: 'sections'