site_name: Mastering the Marketplace
site_url: https://microsoft.github.io/Mastering-the-Marketplace/
repo_url: https://github.com/microsoft/Mastering-the-Marketplace
repo_name: microsoft/Mastering-the-Marketplace
edit_uri: ''
extra_css: 
    - stylesheets/extra.css
nav : 
- Azure Managed Application offers: '/Mastering-the-Marketplace/ama/'
- Container offers for K8s apps: '/Mastering-the-Marketplace/container/'
- Partner Center: '/Mastering-the-Marketplace/partner-center/'
- SaaS offers: '/Mastering-the-Marketplace/saas/'
- SaaS Accelerator: '/Mastering-the-Marketplace/saas-accelerator/'
- Virtual Machine offers: '/Mastering-the-Marketplace/vm/'
- Teams offers: '/Mastering-the-Marketplace/teams/'
- "": "/"
- "": "/"
- "": "/"
- Select your offer type: '/Mastering-the-Marketplace/misc/select-offer-type'
- Choose your learning path: '/Mastering-the-Marketplace/learning-paths/'
- Site change log: '/Mastering-the-Marketplace/misc/change-log'

theme:
  name: material
  custom_dir: overrides
  palette: 
    primary: '#0078D4'
    accent: 'light blue'
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/brands/microsoft
  favicon: favicon.ico
  features:
    - navigation.sections
extra: 
  homepage: https://microsoft.github.io/Mastering-the-Marketplace/
  generator: false
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - toc:
        permalink: "#"
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - search:
        indexing: 'sections'