# Azure Vote UI control
title: Azure ToDo App
global:
  azure:
    billingIdentifier: DONOTMODIFY
    images:
      frontend:
        digest: sha256:ac654125c21e37e2fdb6a5b3c22f1dad4c4628236cf58f8a606d9c5183e4c1c9
        image: todojs
        registry: dsacr01.azurecr.io
      backend:
        digest: sha256:e0b1614551474ee2f3c3ef7c9706b5e19f2107aa36b73c910522af9fa8eb756e
        image: mongo
        registry: dsacr01.azurecr.io

# MongoDB Admin
mongoDBAdmin: admin
mongoDBPassword: password21!!

# Service controls
serviceType: LoadBalancer
appFrontLabel: todoapp
appBackLabel: mongodb

#ingressName
clusterDNS: ""

# how many frontends do we want?
replicaFrontCount: 1
replicaBackCount: 1

## Where it will be deployed
nameSpace: <<ADD namespace>>
